// Code generated by github.com/skipor/gmg - type-safe, fast and handy alternative GoMock generator. DO NOT EDIT.
// Source: github.com/skipor/gmg/examples/3_generate_all_interfaces/3_black_box_test.Third

package mocks_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// NewMockThird creates a new GoMock for github.com/skipor/gmg/examples/3_generate_all_interfaces/3_black_box_test.Third.
func NewMockThird(ctrl *gomock.Controller) *MockThird {
	return &MockThird{ctrl: ctrl}
}

// MockThird is a GoMock of github.com/skipor/gmg/examples/3_generate_all_interfaces/3_black_box_test.Third.
type MockThird struct{ ctrl *gomock.Controller }

// EXPECT returns GoMock recorder.
func (m_ *MockThird) EXPECT() *MockThirdMockRecorder {
	return (*MockThirdMockRecorder)(m_)
}

// Qux implements mocked interface.
func (m_ *MockThird) Qux() {
	m_.ctrl.T.Helper()
	m_.ctrl.Call(m_, "Qux")
	return
}

// MockThirdMockRecorder is the mock recorder for MockThird.
type MockThirdMockRecorder MockThird

//   Qux()
func (r_ *MockThirdMockRecorder) Qux() MockThirdQuxCall {
	r_.ctrl.T.Helper()
	call := r_.ctrl.RecordCallWithMethodType(r_.mock(), "Qux", reflect.TypeOf((*MockThird)(nil).Qux))
	return MockThirdQuxCall{call}
}

// MockThirdQuxCall is type safe wrapper of *gomock.Call.
type MockThirdQuxCall struct{ *gomock.Call }

// DoAndReturn is type safe wrapper of *gomock.Call DoAndReturn.
func (c_ MockThirdQuxCall) DoAndReturn(f func()) MockThirdQuxCall {
	c_.Call.DoAndReturn(f)
	return c_
}

// Do is type safe wrapper of *gomock.Call Do.
func (c_ MockThirdQuxCall) Do(f func()) MockThirdQuxCall {
	c_.Call.Do(f)
	return c_
}

func (r_ *MockThirdMockRecorder) mock() *MockThird {
	return (*MockThird)(r_)
}
