package examples

import (
	"flag"
	"io"
	"io/fs"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/skipor/gmg/internal/testutil"
)

var update bool

func init() {
	flag.BoolVar(&update, "update", false, "Update mocks in examples, instead of check that they are not changed.")
}

func TestExamplesGoGenerate(t *testing.T) {
	if update {
		removeAllGeneratedFiles(t)
	}
	PATH := testutil.TestInstallGmgOnce(t)
	entries, err := os.ReadDir(".")
	require.NoError(t, err, "test dir read")
	for _, ent := range entries {
		if !ent.IsDir() {
			continue
		}
		dir := ent.Name()
		t.Run(dir, func(t *testing.T) {
			if !update {
				diff := vcsDiff(t, dir)
				if diff != "" {
					t.Fatalf("diff before generate:\n%s", diff)
				}
			}
			cmd := exec.Command("go", "generate", "./"+dir+"/...")
			cmd.Env = append(os.Environ(), "GMG_DEBUG=true", PATH)
			out, err := cmd.CombinedOutput()
			t.Logf("%s\n%s", cmd.String(), out)
			require.NoError(t, err, "go generate failed")
			if !update {
				diff := vcsDiff(t, dir)
				if diff != "" {
					t.Fatalf("diff after generate:\n%s", diff)
				}
			} else {
				vcsAddAll(t, dir)
			}
		})
	}
}

func removeAllGeneratedFiles(t *testing.T) {
	err := filepath.Walk(".", func(path string, info fs.FileInfo, err error) error {
		if info.IsDir() {
			return nil
		}
		file, err := os.Open(path)
		require.NoError(t, err, "failed to open %s", path)
		data, err := ioutil.ReadAll(io.LimitReader(file, 128))
		if err != nil && err != io.EOF {
			t.Fatalf("read %s fail: %+v", path, err)
		}
		generated := strings.HasPrefix(string(data), "// Code generated by ")
		if !generated {
			return nil
		}
		err = os.Remove(path)
		require.NoError(t, err, "remove %s", path)
		return nil
	})
	require.NoError(t, err)
}

func vcsDiff(t *testing.T, dir string) string {
	gitAddNew(t, dir)
	cmd := exec.Command("git", "diff", "--exit-code", dir)
	out, err := cmd.CombinedOutput()
	if err != nil {
		_, ok := err.(*exec.ExitError)
		if ok {
			return string(out)
		}
		t.Fatalf("unexpected '%s' fail: %+v", cmd.String(), err)
	}
	return ""
}

// gitAddNew adds untracked files to make them visible in diff.
func gitAddNew(t *testing.T, dir string) {
	cmd := exec.Command("git", "add", "-N", dir)
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "%s\n%s", out)
}

func vcsAddAll(t *testing.T, dir string) {
	cmd := exec.Command("git", "add", "-A", dir)
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "%s\n%s", out)
}
